protected/models/Orders.php
<?php

/**
 * This is the model class for table "orders".
 *
 * The followings are the available columns in table 'orders':
 * @property integer $id
 * @property integer $user_id
 * @property integer $film_id
 * @property string $date
 * @property string $hour
 * @property integer $row
 * @property integer $column
 * @property integer $ticket_price
 */
class Orders extends CActiveRecord {

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'orders';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('user_id, film_id, row, column, ticket_price', 'numerical', 'integerOnly' => true),
            array('date, hour', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, user_id, film_id, date, hour, row, column, ticket_price', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'Հ/Հ',
            'user_id' => 'Հաճախորդ',
            'film_id' => 'Ֆիլմ',
            'date' => 'Ամսաթիվ',
            'hour' => 'Ժամ',
            'row' => 'Շարք',
            'column' => 'Սյուն',
            'ticket_price' => 'Տոմսի արժեքը',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search() {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('film_id', $this->film_id);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('hour', $this->hour, true);
        $criteria->compare('row', $this->row);
        $criteria->compare('column', $this->column);
        $criteria->compare('ticket_price', $this->ticket_price);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Orders the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function getMyOrders($user_id) {
        $criteria = new CDbCriteria;
        $criteria->select = '*';
        $criteria->order = 'id ASC';
        $criteria->condition = 'user_id=:user_id';
        $criteria->params = array(':user_id' => $user_id);
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}

protected/controllers/OrdersController.php
<?php

class OrdersController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column4';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete', 'agendahour', 'place'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Orders;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Orders'])) {
            $model->attributes = $_POST['Orders'];
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Orders'])) {
            $model->attributes = $_POST['Orders'];
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Admin::model()->getPermissionAll() == false) {
            $this->loadModel($id)->delete();
            Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
        }
        if (Admin::model()->getPermission(Yii::app()->user->getId()) == true)
            $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Orders');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Orders('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Orders']))
            $model->attributes = $_GET['Orders'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Orders the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Orders::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Orders $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'orders-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionAgendaHour() {
        $data = Agenda::model()->findAllByAttributes(array('date' => $_POST['date'], 'film_id' => (int) $_POST['film_id']));
        $data = CHtml::listData($data, 'id', 'hour');
        $data['no'] = 'Ընտրել ժամը';
        if (!empty($data)) {
            foreach ($data as $key => $value)
                echo CHtml::tag('option', array('value' => $value), CHtml::encode($value), true);
        } else
            echo CHtml::tag('option', array('value' => 0), 'Օրակարգում չկա ֆիլմը', true);
    }

    public function actionPlace() {
        $data = Orders::model()->findAllByAttributes(array('date' => $_POST['date'], 'film_id' => (int) $_POST['film_id'], 'hour' => $_POST['hour']));
        $array = array();
        foreach ($data as $key => $value) {
            $array[$key]['row'] = $value->row;
            $array[$key]['column'] = $value->column;
        }
        $array[$key]['ticket_price'] = Agenda::model()->findByAttributes(array('date' => $_POST['date'], 'film_id' => (int) $_POST['film_id'], 'hour' => $_POST['hour']))->ticket_price;
        echo CJSON::encode($array);
        Yii::app()->end();
    }

}

protected/views/orders/_form.php
<?php
/* @var $this OrdersController */
/* @var $model Orders */
/* @var $form CActiveForm */
?>
<div class="form">
    <div class ='hall'>
        <div class="close">Close</div>
        <div class="my_halls">
            <h3 style="color: #ffffff">Կինոթատրոնի ազատ և զբաղված տեղերը</h3>
        </div>
        <table style="width: 150px;">
            <tr>
                <td><div style="background:red;width: 50px;height: 20px;"></div></td>
                <td><span>-Զբաղված</span></td>
            </tr>
            <tr>
                <td><div style="background:blue;width: 50px;height: 20px;"></div></td>
                <td><span>-Ազատ</span></td>
            </tr>
        </table>

    </div>
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'orders-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
    ));
    ?>

    <p class="note">Fields with <span class="required">*</span>-ով դաշտերը պարտադիր են</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'user_id'); ?>
        <?php echo $form->dropDownList($model, 'user_id', Users::model()->getUserList()); ?>
        <?php echo $form->error($model, 'user_id'); ?>
    </div>
    <div class="row">
        <?php echo $form->labelEx($model, 'date'); ?>
        <?php
        $this->widget('zii.widgets.jui.CJuiDatePicker', array(
            'name' => 'Orders[date]',
            'value' => $model->date,
            'options' => array(
                'dateFormat' => 'yy-mm-dd',
                'showAnim' => 'slide', //'slide','fold','slideDown','fadeIn','blind','bounce','clip','drop'
                'showButtonPanel' => true,
                'onSelect' => 'js:function(dateText, inst){$("#Orders_film_id").attr("disabled", false);}'
            ),
            'htmlOptions' => array(
                'style' => '',
                'readonly' => 'readonly',
            ),
        ));
        ?>
        <?php echo $form->error($model, 'date'); ?>
    </div>
    <div class="row">
        <?php echo $form->labelEx($model, 'film_id'); ?>
        <?php
        echo $form->dropDownList($model, 'film_id', array(0 => 'Ֆիլմն ընտրված չէ', 'Ֆիլմերի ցանկ' => Films::model()->getFilmList()), array(
            'ajax' => array(
                'type' => 'POST', //request type
                'url' => CController::createUrl('orders/agendahour'),
                'update' => '#Orders_hour',
                'data' => 'js:{date: $("#Orders_date").val(),film_id:$("#Orders_film_id").val() }'
            ))
        );
        ?>
        <?php echo $form->error($model, 'film_id'); ?>
    </div>
    <div class="row">
        <?php echo $form->labelEx($model, 'hour'); ?>

        <?php
        echo $form->dropDownList($model, 'hour', array('0' => 'Ժամը ընտրված չէ', 'Ֆիլմի ժամերը' => ''), array(
            'ajax' => array(
                'type' => 'POST', //request type
                'url' => CController::createUrl('orders/place'),
                'update' => '',
                'data' => 'js:{date: $("#Orders_date").val(),film_id:$("#Orders_film_id").val(),hour:$("#Orders_hour").val() }',
                'success' =>
                'js:function(data){ 
                    $(".chair").css("background-color", "blue");
                    $(".hall").css("display","block");
                    var json = $.parseJSON(data);
                     $.each(json,function(k,v){
                     var chair=".chair_"+v.row+"_"+v.column;
                    $("#Orders_ticket_price").val(v.ticket_price);
                    $(chair).css("background-color", "red");
                    $(chair).attr("disabled", "disabled");
                    
                }); 
                }',
        )));
        ?>
        <?php echo $form->error($model, 'hour'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'row'); ?>
        <?php echo $form->textField($model, 'row', array('readonly' => 'readonly')); ?>
        <?php echo $form->error($model, 'row'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'column'); ?>
        <?php echo $form->textField($model, 'column', array('readonly' => 'readonly')); ?>
        <?php echo $form->error($model, 'column'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'ticket_price'); ?>
        <?php echo $form->textField($model, 'ticket_price',array('readonly' => 'readonly')); ?>
        <?php echo $form->error($model, 'ticket_price'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Ստեղծել' : 'Պահպանել'); ?>
    </div>

    <?php $this->endWidget(); ?>
</div><!-- form -->
<div id="dialog" title="Dialog Title"></div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#Orders_film_id').attr("disabled", true);
        function chair(row, column)
        {
            var text = '<table>';
            for (i = 1; i < row; i++)
            {
                text += '<tr>';
                for (j = 1; j < column; j++)
                {
                    text += '<td><div id="' + i + '" data="' + j + '" class="chair chair_' + i + '_' + j + '"></div></td>';
                }
                text += '</tr>';
            }
            text += '</table>';
            return text;
        }
        $('.my_halls').append(chair(8, 8));
        $(".chair").click(function() {
            var row = $('#Orders_row').val();
            var column = $('#Orders_column').val();
            $(".chair_" + row + "_" + column).css("background-color", "blue");
            $(this).css("background-color", 'red');
            $('#Orders_row').val($(this).attr('id'));
            $('#Orders_column').val($(this).attr('data'));
        });
        $('.close').click(function() {
            $('.hall').css('display', 'none');
        })

    })
</script>

protected/views/orders/_view.php
<?php
/* @var $this OrdersController */
/* @var $data Orders */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo Users::model()->getUserName($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('film_id')); ?>:</b>
	<?php echo Agenda::model()->getFilmName($data->film_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hour')); ?>:</b>
	<?php echo CHtml::encode($data->hour); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('row')); ?>:</b>
	<?php echo CHtml::encode($data->row); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('column')); ?>:</b>
	<?php echo CHtml::encode($data->column); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('ticket_price')); ?>:</b>
	<?php echo CHtml::encode($data->ticket_price); ?>
	<br />

	*/ ?>

</div>

protected/views/orders/admin.php
<?php
/* @var $this OrdersController */
/* @var $model Orders */

$this->breadcrumbs=array(
	'Պատվերներ'=>array('index'),
	'Կառավարում',
);

$this->menu=array(
	array('label'=>'Պատվերների ցանկ', 'url'=>array('index')),
	array('label'=>'Ստեղծել պատվեր', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$('#orders-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'orders-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
        'summaryText' => '',
	'columns'=>array(
		'id',
		'user_id',
		'film_id',
		'date',
		'hour',
		'row',
		'column',
		'ticket_price',
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/orders/create.php
<?php
/* @var $this OrdersController */
/* @var $model Orders */

$this->breadcrumbs=array(
	'Պատերներ'=>array('index'),
	'Ստեղծել',
);

$this->menu=array(
	array('label'=>'Պատվերների ցանկ', 'url'=>array('index')),
	array('label'=>'Պատվերների կառավարում', 'url'=>array('admin')),
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/orders/index.php
<?php

/* @var $this OrdersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Պատվերներ',
);

$this->menu = array(
    array('label' => 'Ստեղծել պատվեր', 'url' => array('create')),
    array('label' => 'Պատվերիների կառավարում', 'url' => array('admin')),
);
?>
<?php

$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
    'summaryText' => '',
));
?>

protected/views/orders/update.php
<?php
/* @var $this OrdersController */
/* @var $model Orders */

$this->breadcrumbs=array(
	'Պատվերներ'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Փոփոխել',
);

$this->menu=array(
	array('label'=>'Պատվերների ցանկ', 'url'=>array('index')),
	array('label'=>'Ստեղծել պատվերներ', 'url'=>array('create')),
	array('label'=>'Տեսնել պատվերը', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Պատվերների կառավարում', 'url'=>array('admin')),
);
?>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/orders/view.php
<?php
/* @var $this OrdersController */
/* @var $model Orders */

$this->breadcrumbs = array(
    'Պատվերներ' => array('index'),
    $model->id,
);

$this->menu = array(
    array('label' => 'Պատվերների ցանկ', 'url' => array('index')),
    array('label' => 'Ստեղծել պատվեր', 'url' => array('create')),
    array('label' => 'Փոփոխել պատվերը', 'url' => array('update', 'id' => $model->id)),
    array('label' => 'Ջնջել պատվերը', 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => 'Are you sure you want to delete this item?')),
    array('label' => 'Պատվերների կառավարում', 'url' => array('admin')),
);
?>

<h1>Տոմս N<?php
    if ($model->row == 1)
        $row_rd = '-ին';
    else
        $row_rd = '-րդ';
    if ($model->column == 1)
        $column_rd = '-ին';
    else
        $column_rd = '-րդ';
    echo $model->id;
    echo '<br>' . $model->row . $row_rd . ' շարքի ' . $model->column . $column_rd . ' տեղի համար` գինը ' . $model->ticket_price . ' դրամ:'; {
        
    };
    ?></h1>
    <?php
$this->widget('zii.widgets.CDetailView', array(
    'data' => $model,
    'attributes' => array(
        'id',
        array('name' => 'user_id',
            'value' => Users::model()->getUserName($model->user_id)),
        array('name' => 'film_id',
            'value' => Agenda::model()->getFilmName($model->film_id)),
        'date',
        'hour',
    ),
));
?>
<div class ='hall_by_film'>
    <div class="close">Close</div>
    <div class="my_halls">
        <h3 style="color: #ffffff">Կինոթատրոնում զբաղեցրած տեղը</h3>
        <?php
        $chair = array($model->row . "_" . $model->column);
        $row = 8;
        $column = 8;
        $text = '<table>';
        for ($i = 1; $i < $row; $i++) {
            $text .= '<tr>';
            for ($j = 1; $j < $column; $j++) {
                if (in_array($i . '_' . $j, $chair)) {
                    $text .= '<td><div id = "' . $i . '" data = "' . $j . '" style="background:red" class = "chair"></div></td>';
                } else {
                    $text .= '<td><div id = "' . $i . '" data = "' . $j . '" style="background:blue" class = "chair"></div></td>';
                }
            }
            $text .= '</tr>';
        }
        $text .= '</table>';
        echo $text;
        ?>
    </div>
    <table style="width: 150px;">
        <tr>
            <td><div style="background:red;width: 50px;height: 20px;"></div></td>
            <td><span>-Զբաղված</span></td>
        </tr>
        <tr>
            <td><div style="background:blue;width: 50px;height: 20px;"></div></td>
            <td><span>-Ազատ</span></td>
        </tr>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".hall_by_film").css("display", "block");
        $('.close').click(function() {
            $('.hall_by_film').css('display', 'none ');
        })

    })
</script>