protected/models/Films.php
<?php

/**
 * This is the model class for table "films".
 *
 * The followings are the available columns in table 'films':
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $genre
 * @property string $image
 * @property string $date
 * @property string $director
 * @property string $country
 * @property integer $length
 */
class Films extends CActiveRecord {

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'films';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('length', 'numerical', 'integerOnly' => true),
            array('name, image, director, country,genre', 'length', 'max' => 255),
            array('description, date', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, name, description, genre,image, date, director, country, length', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'Հ/Հ',
            'name' => 'Ֆիլմի անվանում',
            'description' => 'Ֆիլմի նկարագրություն',
            'genre' => 'Ժանր',
            'image' => 'Ֆիլմի նկար',
            'date' => 'Ստեղծման ամսաթիվ',
            'director' => 'Ռեժիսոր',
            'country' => 'Երկիր',
            'length' => 'Տևողություն',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search() {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('genre', $this->image, true);
        $criteria->compare('image', $this->image, true);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('director', $this->director, true);
        $criteria->compare('country', $this->country, true);
        $criteria->compare('length', $this->length);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Films the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function getFilmList() {
        return CHtml::listData($this->findAll(), 'id', 'name');
    }

}

protected/controllers/FilmsController.php
<?php

class FilmsController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column4';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete'),
                'users' => array('@'),
            ),
           array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Films;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Films'])) {
            $model->attributes = $_POST['Films'];
            $imageUploadFile = CUploadedFile::getInstance($model, 'image');
            if ($imageUploadFile !== null) { // only do if file is really uploaded
                $imageFileName = mktime() . '_' . $imageUploadFile->name;
                $model->image = '/images/' . $imageFileName;
            }
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                if ($imageUploadFile !== null) // validate to save file
                    $imageUploadFile->saveAs('images/' . $imageFileName);
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                if ($imageUploadFile !== null) // validate to save file
                    $imageUploadFile->saveAs('images/' . $imageFileName);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Films'])) {
            $model->attributes = $_POST['Films'];
            $imageUploadFile = CUploadedFile::getInstance($model, 'image');
            if ($imageUploadFile !== null) { // only do if file is really uploaded
                $imageFileName = mktime() . '_' . $imageUploadFile->name;
                $model->image = '/images/' . $imageFileName;
            }
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                if ($imageUploadFile !== null) // validate to save file
                    $imageUploadFile->saveAs('images/' . $imageFileName);
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                if ($imageUploadFile !== null) // validate to save file
                    $imageUploadFile->saveAs('images/' . $imageFileName);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Admin::model()->getPermissionAll() == false) {
            $this->loadModel($id)->delete();
            Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
        }
        if (Admin::model()->getPermission(Yii::app()->user->getId()) == true)
            $this->loadModel($id)->delete();
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Films');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Films('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Films']))
            $model->attributes = $_GET['Films'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Films the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Films::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Films $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'films-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/controllers/GenreController.php
<?php

class GenreController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column4';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'index', 'view', 'admin', 'delete'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Genre;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Genre'])) {
            $model->attributes = $_POST['Genre'];
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Genre'])) {
            $model->attributes = $_POST['Genre'];
            if (Admin::model()->getPermissionAll() == false) {
                $model->save(false);
                Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
                $this->redirect(array('view', 'id' => $model->id));
            }
            if (Admin::model()->getPermission(Yii::app()->user->getId()) == true) {
                $model->save(false);
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Admin::model()->getPermissionAll() == false) {
            $this->loadModel($id)->delete();
            Admin::model()->getChangePermissionTrue(Yii::app()->user->getId());
        }
        if (Admin::model()->getPermission(Yii::app()->user->getId()) == true)
            $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Genre');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Genre('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Genre']))
            $model->attributes = $_GET['Genre'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Genre the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Genre::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Genre $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'genre-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/films/_form.php
<?php
/* @var $this FilmsController */
/* @var $model Films */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id' => 'upload-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
        'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>

	<p class="note"><span class="required">*</span>-ով դաշտերը պարտադիր են</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>
        <div class="row">
		<?php echo $form->labelEx($model,'genre'); ?>
		<?php echo $form->dropDownList($model,'genre', Genre::model()->getGenreList()); ?>
                <?php echo CHtml::submitButton('Ավելացնել ֆիլմի ժանր',array('submit' => '/genre/create')); ?>
		<?php echo $form->error($model,'genre'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'image'); ?>
		<?php echo $form->textField($model,'image',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->fileField($model, 'image');?>
                <?php echo $form->error($model,'image'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date'); ?>
            <?php
        $this->widget('zii.widgets.jui.CJuiDatePicker', array(
            'name' => 'Films[date]',
            'value' => $model->date,
            'options' => array(
                'dateFormat' => 'yy-mm-dd',
                'showAnim' => 'slide', //'slide','fold','slideDown','fadeIn','blind','bounce','clip','drop'
                'showButtonPanel' => true,
            ),
            'htmlOptions' => array(
                'style' => ''
            ),
        ));
        ?>
		
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'director'); ?>
		<?php echo $form->textField($model,'director',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'director'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'country'); ?>
		<?php echo $form->textField($model,'country',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'country'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'length'); ?>
		<?php echo $form->textField($model,'length'); ?>
		<?php echo $form->error($model,'length'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Ստեղծել' : 'Պահպանել'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/films/_view.php
<?php
/* @var $this FilmsController */
/* @var $data Films */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('genre')); ?>:</b>
	<?php echo CHtml::encode($data->genre); ?>
	<br />
        <b><?php echo CHtml::encode($data->getAttributeLabel('image')); ?>:</b>
	<?php echo CHtml::encode($data->image); ?>
	<br />
	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('director')); ?>:</b>
	<?php echo CHtml::encode($data->director); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('country')); ?>:</b>
	<?php echo CHtml::encode($data->country); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('length')); ?>:</b>
	<?php echo CHtml::encode($data->length); ?>
	<br />

	*/ ?>

</div>

protected/views/films/admin.php
<?php
/* @var $this FilmsController */
/* @var $model Films */

$this->breadcrumbs=array(
	'Ֆիլմեր'=>array('index'),
	'Կառավարում',
);

$this->menu=array(
	array('label'=>'Ֆիլմերի ցանկ', 'url'=>array('index')),
	array('label'=>'Ստեղծել ֆիլմ', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$('#films-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'films-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
        'summaryText' => '',
	'columns'=>array(
		'id',
		'name',
		'description',
                //'genre',
		//'image',
		'date',
		'director',
		/*
		'country',
		'length',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/films/create.php
<?php
/* @var $this FilmsController */
/* @var $model Films */

$this->breadcrumbs=array(
	'Ֆիլմեր'=>array('index'),
	'Ստեղծել',
);

$this->menu=array(
	array('label'=>'Ֆիլմերի ցանկ', 'url'=>array('index')),
	array('label'=>'Ֆիլմերի կառավարում', 'url'=>array('admin')),
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/films/index.php
<?php
/* @var $this FilmsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Ֆիլմեր',
);

$this->menu=array(
	array('label'=>'Ստեղծել ֆիլմ', 'url'=>array('create')),
	array('label'=>'Ֆիլմերի կառավարում', 'url'=>array('admin')),
);
?>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
        'summaryText' => '',
)); ?>

protected/views/films/update.php
<?php
/* @var $this FilmsController */
/* @var $model Films */

$this->breadcrumbs=array(
	'Ֆիլմեր'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Փոփոխել',
);

$this->menu=array(
	array('label'=>'Ֆիլմերի ցանկ', 'url'=>array('index')),
	array('label'=>'Ստեղծել ֆիլմ', 'url'=>array('create')),
	array('label'=>'Տեսնել ֆիլմը', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Ֆիլմերի կառավարում', 'url'=>array('admin')),
);
?>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/films/view.php
<?php
/* @var $this FilmsController */
/* @var $model Films */

$this->breadcrumbs = array(
    'Ֆիլմեր' => array('index'),
    $model->name,
);

$this->menu = array(
    array('label' => 'Ֆիլմերի ցանկ', 'url' => array('index')),
    array('label' => 'Ստեղծել ֆիլմ', 'url' => array('create')),
    array('label' => 'Փոփոխել ֆիլմը', 'url' => array('update', 'id' => $model->id)),
    array('label' => 'Ջնջել ֆիլմը', 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => 'Are you sure you want to delete this item?')),
    array('label' => 'Ֆիլմերի կառավարում', 'url' => array('admin')),
);
?>
<?php
$this->widget('zii.widgets.CDetailView', array(
    'data' => $model,
    'attributes' => array(
        'id',
        'name',
        'description',
        'genre',
        'image',
        'date',
        'director',
        'country',
        'length',
    ),
));
?>